use_frameworks!

platform :ios, '9.0'

target 'ScrollingFormHelper_Example' do
  pod 'ScrollingFormHelper', :path => '../'

  target 'ScrollingFormHelper_Tests' do
    inherit! :search_paths

    
  end
end
